### ISSUE TITLE
Undefined method `exists?' for Dir:Class

### ISSUE THREAD

**Issue by markst** [zalazara/pod-template-xcframework#1]
This template is great, but is it constrained to a particular version of cocoapods?

Having the following issue:

```
mt@mt-mba abc % pod --version
1.11.3
```

```shell
mt@mt-mba Developer % pod lib create Snowplow --template-url="https://github.com/zalazara/pod-template-xcframework.git"

Cloning `https://github.com/zalazara/pod-template-xcframework.git` into `Snowplow`.
Configuring Snowplow template.
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
/Users/mt/Developer/Snowplow/setup/ProjectManipulator.rb:143:in `block in replace_internal_project_settings': undefined method `exists?' for Dir:Class (NoMethodError)

        next if Dir.exists? name
                   ^^^^^^^^
Did you mean?  exist?
	from /Users/mt/Developer/Snowplow/setup/ProjectManipulator.rb:142:in `each'
	from /Users/mt/Developer/Snowplow/setup/ProjectManipulator.rb:142:in `replace_internal_project_settings'
	from /Users/mt/Developer/Snowplow/setup/ProjectManipulator.rb:29:in `run'
	from /Users/mt/Developer/Snowplow/setup/ConfigureSwift.rb:24:in `perform'
	from /Users/mt/Developer/Snowplow/setup/ConfigureSwift.rb:7:in `perform'
	from /Users/mt/Developer/Snowplow/setup/TemplateConfigurator.rb:72:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/zalazara/pod-template-xcframework.git`.
To learn more about creating a new pod, see `https://guides.cocoapods.org/making/making-a-cocoapod`.
```

**Comment by zalazara** [comment]
Hi! This error is about Ruby version, what is your ruby version?

**Comment by markst** [comment]
oh I see. here's my version:

```shell
mt@mt-mba ~ % ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
mt@mt-mba ~ % rbenv --version
rbenv 1.2.0
```

**Comment by zalazara** [comment]
I checked this template in Ruby 3.2.2, and it did not work in this version, but it worked correctly in Ruby 3.1.2. I'm going to upgrade this template to work correctly in Ruby 3.2.2.

**Comment by zalazara** [comment]
Fixed template for Ruby 3.2.2

**Comment by markst** [comment]
Thanks mate!
